const reminderResponses: string[] = [
    "Ding ding! Your reminder is here, $NPUB!",
    "$NPUB, guess what? It's reminder time!",
    "Boom! You asked for this reminder, $NPUB.",
    "Hey, $NPUB! Remember this? You should.",
    "Your wish is my command—here’s your reminder, $NPUB.",
    "Peek-a-boo! I remembered for you, $NPUB!",
    "Voilà! Your reminder has arrived, $NPUB.",
    "Knock knock! Who’s there? A reminder for $NPUB!",
    "Oh look, a wild reminder appears for $NPUB!",
    "$NPUB, remember when you asked me to remind you? Yeah, here it is.",
    "Time’s up! Here’s your reminder, $NPUB!",
    "Your friendly reminder delivery service is here, $NPUB.",
    "Here’s your reminder, hot and fresh, $NPUB!",
    "Surprise! It’s reminder o’clock, $NPUB!",
    "Remind-o-rama! Here you go, $NPUB!",
    "I didn't forget! Here's your reminder, $NPUB.",
    "Alright, alright! Here's that reminder, $NPUB.",
    "You rang? Here’s your reminder, $NPUB!",
    "Just in time! Your reminder is here, $NPUB.",
    "Attention, $NPUB! A reminder has landed.",
    "I’m the reminder bot, and I approve this reminder for $NPUB.",
    "The reminder fairy has sprinkled $NPUB with memory dust!",
    "Your reminder is here, $NPUB. Handle with care!",
    "Mission accomplished! Here’s your reminder, $NPUB.",
    "I hope this reminder finds you well, $NPUB.",
    "I’m a bot of my word. Here’s your reminder, $NPUB!",
    "A reminder for $NPUB, with love from the bot.",
    "You waited, and I delivered—a reminder, $NPUB!",
    "Here’s your reminder, $NPUB. Now go be awesome!",
    "Beep boop! Here’s your reminder, $NPUB!",
    "I remembered, $NPUB! Did you? Here’s your reminder.",
    "Just me, your friendly bot, delivering a reminder to $NPUB!",
    "Hey, look! A reminder for $NPUB!",
    "It’s a bird! It’s a plane! No, it’s a reminder for $NPUB!",
    "I’m not saying I’m the best reminder bot, but... here’s your reminder, $NPUB.",
    "This reminder is as fresh as a daisy, $NPUB.",
    "A reminder has appeared in your feed, $NPUB. Act accordingly!",
    "I brought you a reminder, $NPUB. No strings attached!",
    "I’m just a bot, standing in front of $NPUB, reminding them.",
    "This reminder is brought to you by past-you, $NPUB.",
    "Serving you a fresh reminder, just like you asked, $NPUB.",
    "A reminder, straight from the cloud for $NPUB.",
    "This is not a drill—your reminder is here, $NPUB!",
    "Would you look at that? A reminder for $NPUB!",
    "Remember me? I’m your reminder, $NPUB!",
    "A reminder has entered the chat for $NPUB.",
    "Guess who’s back? Back again. With a reminder for $NPUB!",
    "Just me, hanging out, reminding $NPUB.",
    "Knock knock. Who’s there? A reminder for $NPUB!",
    "I’d say something clever, but here’s a reminder instead, $NPUB.",
    "Look at me, all responsible with this reminder for $NPUB.",
    "I’m back! And I brought a reminder for $NPUB.",
    "Ta-da! Your reminder is ready, $NPUB.",
    "Guess who didn’t forget? Me. Reminder time, $NPUB!",
    "Here’s your reminder, fresh off the press, $NPUB.",
    "This reminder is brought to you by... me, $NPUB.",
    "Time for a reminder! Here ya go, $NPUB.",
    "And here it is, a reminder with a side of awesome for $NPUB.",
    "You asked, I delivered—a reminder, $NPUB!",
    "I’ve got something for you—a reminder, $NPUB!",
    "Did someone order a reminder? Because it’s here, $NPUB.",
    "This reminder is as fresh as morning dew, $NPUB.",
    "Your reminder is here, and it’s fabulous, $NPUB.",
    "A reminder a day keeps the forgetting away, $NPUB.",
    "And now, the moment you’ve been waiting for—a reminder, $NPUB!",
    "This just in—your reminder, $NPUB!",
    "The reminder you ordered has been delivered, $NPUB.",
    "This is your reminder, $NPUB. No takebacks!",
    "Bringing you a reminder, as promised, $NPUB.",
    "Your reminder has arrived, fashionably on time, $NPUB.",
    "A reminder! I remembered. Shocking, right, $NPUB?",
    "Behold! The reminder has arrived for $NPUB.",
    "You told me to remind you, so here it is, $NPUB!",
    "Buckle up, $NPUB! Here’s your reminder.",
    "I’d ask if you remember this, but hey—that’s my job, $NPUB!",
    "By the power vested in me, I remind you of this, $NPUB!",
    "This reminder has been certified fresh for $NPUB.",
    "Hold up—remember this? You should, $NPUB!",
    "Your reminder has entered the room, $NPUB.",
    "Here’s your reminder, and a virtual high-five, $NPUB!",
    "A reminder for you, straight from the bot’s heart, $NPUB.",
    "The prophecy has been fulfilled—a reminder for $NPUB!",
    "$NPUB, guess what? Reminder time!",
    "Don’t say I never did anything for you—here’s a reminder, $NPUB.",
    "I’m not here to judge, just to remind $NPUB.",
    "Look who’s punctual—your reminder for $NPUB!",
    "The reminder train has arrived at the station, $NPUB.",
    "I brought a reminder. And snacks. Just kidding, only the reminder, $NPUB.",
    "I remembered! Here’s your reminder, $NPUB.",
    "Your reminder has arrived, and it’s not late, $NPUB!",
    "I’m a bot of my word—here’s your reminder, $NPUB.",
    "Boom! A reminder, just for you, $NPUB.",
    "This is your reminder, straight from the bot’s mouth, $NPUB.",
    "You wanted it? You got it! Reminder time, $NPUB!",
    "I’m a reminder bot, not a miracle worker. But here’s a reminder, $NPUB!",
    "I brought you a little something—a reminder, $NPUB!",
    "The reminder fairy has struck again for $NPUB!",
    "Time flies, but reminders land—like this one, $NPUB!"
];

function getRandomReminder(npub: string): string {
    const randomIndex = Math.floor(Math.random() * reminderResponses.length);
    return reminderResponses[randomIndex].replace("$NPUB", `nostr:${npub}`);
}

export { getRandomReminder };